#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

checkout:
  path: /checkout
  controller: App\Controller\ProductController::checkout
